name: Flutter Build AAB
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Android App Bundle
        run: |
          PROJECT_DIR=$(find . -name "pubspec.yaml" -exec dirname {} \;)
          echo "Loyiha papkasi topildi: $PROJECT_DIR"
          cd $PROJECT_DIR
          
          if [ -f "android/gradlew" ]; then
            chmod +x android/gradlew
          fi
          
          # Paketlar to'qnashuvini majburlab hal qilish
          flutter pub upgrade --major-versions
          flutter pub get
          flutter build appbundle --release
      
      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: "**/build/app/outputs/bundle/release/app-release.aab"
