name: Flutter Build AAB
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Locate and Fix Gradle Permissions
        run: |
          GRADLE_PATH=$(find . -name gradlew)
          if [ -n "$GRADLE_PATH" ]; then
            chmod +x "$GRADLE_PATH"
            cd $(dirname "$GRADLE_PATH")/..
            flutter pub get
            flutter build appbundle --release
          else
            echo "Error: gradlew file not found!"
            exit 1
          fi
      
      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: "**/build/app/outputs/bundle/release/app-release.aab"
